### ISSUE TITLE
Device is offline

### ISSUE THREAD

**Issue by thoithoi58** [bitstuffing/tplink-tapo#2] opened 2022-11-03 16:11 UTC
Hi,

There's something wrong with move method. When I call it, it returned `'Device is offline` error. Please take a look

**Comment by bitstuffing** [comment] 2022-11-04 16:02
Hi @thoithoi58, so... the problem is the client or the remote API? 
I think you should take into account that this python library is for development uses only and for personal investigations, but, this python library consumes an UNOFFICIAL API without any kind of official support. 

If you don't append more information which could indicates that this is an issue or problem with the library... I will close this issue.

Thanks for your understanding.

Greetings

**Closed as completed** 2022-11-05 12:24 UTC
